### PR TITLE
Add name arg to get_label and get_groups

### PR DESCRIPTION
**Pull request by rowanseymour**
To match https://github.com/nyaruka/rapidpro/pull/888

### CODE REVIEW

**Review by nicpottier — COMMENTED** [review]
What does specifying both a uuid and name mean exactly? That the group with that uuid has that name?

**Comment by rowanseymour** [comment]
Yeah.. you'd typically use one or the other

**Comment by nicpottier** [comment]
Seems kinda weird no? Maybe we should disallow passing both in the API?

**Comment by rowanseymour** [comment]
We're treating name like an identifier - so yeah there's no reason to provide 2 different types of identifier and that would be weird. I'm not completely convinced it needs to be an error case but that is pretty easily achieved using the `exclusive_params` attribute of `ListAPIMixin` on the RapidPro side.

**Comment by nicpottier** [comment]
My vote would be to remove the option of having both, because it fails the "minimum functionality possible" test for the API. :)

**Comment by rowanseymour** [comment]
Fair nuff

**Pull request merged**
